data:
  class_path: slow_diffusion.fashionmnist.FashionMNISTDataModule
  init_args:
    bs: 512
    n_workers: -1
model:
  act: torch.nn.SiLU
  color_channels: 1
  lr: 0.0040000000000000001
  n_blocks:
    - 3
    - 2
    - 1
    - 1
    - 1
    - 1
  nfs:
    - 128
    - 256
    - 384
    - 512
    - 768
  res_block_cls: NonPreactResBlock
trainer:
  callbacks:
    - class_path: slow_diffusion.ddpm.DDPMCallback
    - class_path: CustomModelCheckpoint
      init_args:
        dirpath: gs://slow_diffusion/training_runs/fashion_mnist_n3090
        filename: ckpt-{epoch:02d}-{global_step}-{test_loss}
        monitor: test_loss
        save_top_k: 1
    - class_path: slow_diffusion.monitoring.MonitorCallback
      init_args:
        gloms:
          lr: trainer.optimizers.0.param_groups.0.lr
  default_root_dir: .lightning_root_dir
  log_every_n_steps: 5
  logger:
    class_path: lightning.pytorch.loggers.WandbLogger
    init_args:
      project: slow_diffusion
  max_epochs: 25
  precision: bf16-mixed
