# lightning.pytorch==2.3.3
trainer:
  max_epochs: 25
  precision: "bf16"
  # This might introduce latency, but I want to be extremely sure that the
  # loss curvature is initially very smooth for a small dataset to validate
  # potential training issues later on
  log_every_n_steps: 1
  default_root_dir: gs://slow_diffusion
  logger:
    class_path: lightning.pytorch.loggers.WandbLogger
    init_args:
      project: "slow_diffusion"
  callbacks:
    - class_path: lightning.pytorch.callbacks.ModelCheckpoint
      init_args:
        every_n_train_steps: 100 # too often, just to test the gcs integration
        # monitor: "test_loss" # not compatible with every_n_train_steps < epoch
model:
  nfs: [224, 448, 672, 896]
  n_blocks: [3, 2, 2, 1, 1]
  color_channels: 1
  lr: 0.004
data:
  class_path: slow_diffusion.fashionmnist.FashionMNISTDataModule
  init_args:
    bs: 256
    n_workers: -1
