# lightning.pytorch==2.3.3
trainer:
  default_root_dir: .lightning_root_dir
  max_epochs: 25
  precision: "bf16-mixed"
  # This might introduce latency, but I want to be extremely sure that the
  # loss curvature is initially very smooth for a small dataset to validate
  # potential training issues later on
  log_every_n_steps: 1
  logger:
    class_path: lightning.pytorch.loggers.WandbLogger
    init_args:
      project: "slow_diffusion"
  callbacks:
    - class_path: slow_diffusion.ddpm.DDPMCallback
    - class_path: CustomModelCheckpoint
      init_args:
        dirpath: "gs://slow_diffusion/training_runs/fashion_mnist_n3090"
        filename: "ckpt-{epoch:02d}-{global_step}-{test_loss}"
        save_top_k: 1
        monitor: "test_loss"
    - class_path: slow_diffusion.monitoring.MonitorCallback
      init_args:
        lr: "trainer.optimizers.0.param_groups.0.lr"
    - class_path: CountDeadUnitsCallback
    - class_path: StatsCallback
      init_args:
        mod_filter: "convs"
model:
  nfs: [224, 448, 672, 896]
  n_blocks: [3, 2, 2, 1, 1]
  color_channels: 1
  lr: 0.004
data:
  class_path: slow_diffusion.fashionmnist.FashionMNISTDataModule
  init_args:
    bs: 256
    n_workers: -1
