# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/05_fashion_mnist.ipynb.

# %% auto 0
__all__ = ['fashion_mnist_noisify']

# %% ../nbs/05_fashion_mnist.ipynb 2
import torch
import torchvision.transforms.functional as F

from .data import DiffusionDataModule, noisify, show_images

# %% ../nbs/05_fashion_mnist.ipynb 3
def fashion_mnist_noisify(x_0):
    x_0 = F.convert_image_dtype(x_0, torch.float)
    # zero-center so that the mean does not change after adding noise
    x_0 -= 0.5
    return noisify(x_0)
