# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/04_fashion_mnist.ipynb.

# %% auto 0
__all__ = ['FashionMNISTDataModule']

# %% ../nbs/04_fashion_mnist.ipynb 2
import lightning as L
import torch
import torchvision.transforms.functional as F

from .data import DiffusionDataModule, noisify, show_images
from .training import UnetLightning

# %% ../nbs/04_fashion_mnist.ipynb 3
class FashionMNISTDataModule(DiffusionDataModule):
    def __init__(self, bs):
        super().__init__(
            "fashion_mnist",
            bs,
            img_size=(32, 32),
        )

    def noisify_fn(self, x_0):
        x_0 = F.convert_image_dtype(x_0, torch.float)
        # zero-center so that the mean does not change after adding noise
        x_0 -= 0.5
        return noisify(x_0)
