# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/06_initialization.ipynb.

# %% auto 0
__all__ = []

# %% ../nbs/06_initialization.ipynb 2
import math
from functools import singledispatch
from typing import Sequence, TypeAlias

import matplotlib.pyplot as plt
import numpy as np
import torch
from beartype import beartype
from jaxtyping import Float, Int, jaxtyped
from torch import Tensor, nn

from .fashionmnist import TinyFashionMNISTDataModule
from .model import ConvBlock
