# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/05_monitoring.ipynb.

# %% auto 0
__all__ = ['MonitorCallback', 'CountDeadUnitsCallback']

# %% ../nbs/05_monitoring.ipynb 3
class MonitorCallback(L.Callback):
    def __init__(self, /, **gloms):
        super().__init__()
        if not gloms:
            raise ValueError
        self.gloms = gloms

    def on_train_batch_end(self, trainer, pl_module, outputs, batch, batch_idx):
        args = Namespace(
            trainer=trainer,
            pl_module=pl_module,
            outputs=outputs,
            batch=batch,
            batch_idx=batch_idx,
        )
        for name, spec in self.gloms.items():
            self.log(name, glom(args, spec))

# %% ../nbs/05_monitoring.ipynb 4
class CountDeadUnitsCallback(L.Callback):
    def __init__(self):
        super().__init__()

    def on_train_batch_end(self, trainer, pl_module, outputs, batch, batch_idx):
        breakpoint()
